version: "3.7"

services:
  ui:
    build:
      context: .
      dockerfile: ironprocessing/Dockerfile
    ports:
      - 4200:80
    restart: on-failure
    depends_on:
      - "api"
  api:
    build:
      context: backend/ironprocessing/
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - ConnectionStrings__PostgresDb=Server=postgres;Database=Ironprocessing;Username=ad_user;Password=135531;Port=5432
    depends_on:
      - "postgres"

  postgres:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=ad_user
      - POSTGRES_PASSWORD=135531
      - POSTGRES_DB=Advertisment
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: